### ISSUE TITLE
Support for SASS

### ISSUE THREAD

**Issue by AchoArnold** [rbtech/css-purge#10]
Is it possible for me to purge `.scss` files?

**Comment by AndrewEQ** [comment]
I haven't tried but if they purely contain CSS, then possibly but I doubt you just have pure CSS in a .scss file. You could purge the CSS output of your SASS.

**Comment by wardpeet** [comment]
I don't see why you want this? just run it on the compiled (css) files? It's pretty common to have multiple properties in sass:
color: #000
@if $something {
color: #fff;
}

**Comment by AndrewEQ** [comment]
Agree with @wardpeet, we may decide to add support for this in the future but it really isn't necessary right now, more of a luxury.
