### ISSUE TITLE
!important rules are mis-prioritized

### ISSUE THREAD

**Issue by reznik-d** [rbtech/css-purge#16]
That's the input CSS:
`.class{
	border-right: 0 !important;
	border-right: 100000000px;
}`

That's the output:
`.class{border-right:100000000px}`

How to resolve this? I have a HUUUUUGE CSS file with many of !important statements.

**Comment by AndrewEQ** [comment]
Bad CSS writer *smacks reznik-d's hands with a keyboard*; if its soo important, why write another rule under it? :P The immediate solution will be for you to correct your CSS...

I shall have to create an option for this feature.

**Comment by AndrewEQ** [comment]
Ok Reznik, just pushed a patch to resolve this, lemme know how it goes!

**Comment by reznik-d** [comment]
Thanks! It works.
