### ISSUE TITLE
How to input multiple files, remove duplicates and not have them combine into a single file

### ISSUE THREAD

**Issue by tyler-barnes** [rbtech/css-purge#18]
Is there a way to take A.css and B.css, remove B's duplicate css from A, and keep A and B as separate files in the end?

**Comment by AndrewEQ** [comment]
Hey Tyler, not at the moment but I'll consider this as a future feature, thanks for the input.

**Comment by silkphntm** [comment]
Man was just looking for the exact same thing

**Comment by AndrewEQ** [comment]
Hehe, sorry man, so its +2 so far for this feature.

**Comment by AndrewEQ** [comment]
Oh btw, I was just thinking that you could use gulp to do this: https://www.npmjs.com/package/gulp-css-purge

**Comment by AndrewEQ** [comment]
```javascript
var gulp = require('gulp'),
    concat = require('gulp-concat'),
    purge = require('gulp-css-purge');

gulp.task('default', function() {
  return gulp
        .src(['./**/*.css']) //input css
        .pipe(concat('main.css')) //merge into single css file - remove if you want to process output into separate files
        .pipe(purge({
            trim : true,
            shorten : true,
            verbose : true
        }))
        .pipe(gulp.dest('build/css')) //output folder
});
```

**Comment by DustinJSilk** [comment]
_used wrong github account up there_
I actually went the long way around and exported a third css file with the common selectors to be removed. This was my solution using grunt-postcss:

```javascript
(() => {
              let duplicateStyles = [];
              try {
                // Strip selectors from file
                const file = fs.readFileSync(__dirname +
                    '/static/css/duplicated_styles.css', 'utf8');
                duplicateStyles = file.match(/\.(\.|\w|-|\d|\s)+(?=\{)/g);
              } catch (err) {
                console.warn(err);
              }
              const options = {rulesToRemove: duplicateStyles, map: false};
              return require('css-byebye')(options)
            })()
```

This was all because the library I have to use exports 50kb of selectors with the required variables making it difficult to export 2 css files.

I might go back to what you've just suggested. Thanks!

**Comment by AndrewEQ** [comment]
Sorry about that, there is a grunt version of the plugin if that helps: https://github.com/dominikwilkowski/grunt-css-purge

**Comment by AndrewEQ** [comment]
Oh wait, sorry guys, read your original comment again, it won't remove B from A, just process A and B separately, removing their own duplicates if any from themselves. So it does A reduced and B reduced instead of what you requested A - B = A reduced and B.

**Comment by usman33** [comment]
Any solution to the original problem yet? Removing duplicates across multiple files ?

**Comment by jombles** [comment]
I am also interested in this functionality. Are there any updates?

**Comment by AndrewEQ** [comment]
hey guys, sorry been really busy these past few months, recovered from the flu too, I'll try my best to take a look at things in the coming weekends

**Comment by alex-balint** [comment]
Hi guys, same problem here... found this thing, maybe it helps (not tried yet, though): postcss-discard 

They say:
-----------------------------------------
Diffing stylesheets
postcss(discard({css: 'STYLES TO BE REMOVED'})).process('ORIGINAL CSS').css;
-----------------------------------------

**Comment by prikr** [comment]
Reopening, because i'm still searching for a feature like this.
