### ISSUE TITLE
CSS Hack - *crossed*

### ISSUE THREAD

**Issue by cr0ss** [rbtech/css-purge#19]
Hello, I've updated my css-purge to latest 3.0.4 and noticing following problems:

Original CSS:
`border: 0.2em solid #F0F2FA;`

Purged CSS:
`border: 0 solid #F0F2FA;`

Original CSS:
```
background-color: #FFF;
border-top-left-radius: 5px;
border-top-right-radius: 5px;
border-bottom-left-radius: 5px;
border-bottom-right-radius: 5px;
border-bottom-right-radius: 5px;
border-top-right-radius: 5px;
border-bottom-left-radius: 5px;
border-top-left-radius: 5px;
margin-bottom: 20px;
padding: 20px;
clear: both; *crossed*
overflow: hidden; *crossed*
background-color: #04003F;
position: relative;
text-decoration: none;
position: relative;
padding-bottom: 60px;
overflow: hidden;
clear: none;
```

Purged CSS:
```
border-top-right-radius: 5px;
border-bottom-right-radius: 5px;
border-top-right-radius: 5px;
border-top-left-radius: 5px;
margin-bottom: 20px;
padding: 20px 20px 60px;
clear: both;
overflow: hidden;
background-color: #04003F;
position: relative;
text-decoration: none;
overflow: hidden;
```

So there are 2 problems:
1. "border" styles with 0.2em getting cut off to 0
2. Cleaning dup of "clear" being decided wrong

Any workaround on this?

**Comment by AndrewEQ** [comment]
Hi there,

You can explicitly set in the "reduce_declarations.json" which css properties are to be evaluated, so just add in the ones you want. Therefore, you could leave out "clear" and "border" for now as a workaround.

1. I'll have to have a look at that
2. Don't think I've catered for "*crossed*", what is that for? Is it a hack?

**Comment by AndrewEQ** [comment]
Another set of workarounds could be to adjust these settings in config_css.json:

        "shorten_border": false,
        "shorten_zero": false,
        "zero_units": "em, ex, %, px, cm, mm, in, pt, pc, ch, rem, vh, vw, vmin, vmax",
        "zero_ignore_declaration": ['border'],

**Comment by AndrewEQ** [comment]
Hey @cr0ss, so its definitely *crossed*, is this your own code for a processor?
