### ISSUE TITLE
display: flex property issue

### ISSUE THREAD

**Issue by do-web** [rbtech/css-purge#23]
input test file:

`
.footer {
  padding: 50px 0;
  background: #d6d6d6;
}

.footer__navigation ul {
  list-style-type: none;
  padding: 0;
  margin: 0;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin: 0 -15px;
}

.footer__navigation li {
  padding: 0 15px;
}

.navigation__main>nav {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  margin: 10px -15px 0;
}

.footer {
  padding: 50px 0;
  background: #d6d6d6;
}

.footer__navigation ul {
  list-style-type: none;
  padding: 0;
  margin: 0;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin: 0 -15px;
}

.footer__navigation li {
  padding: 0 15px;
}

.navigation__main>nav {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  margin: 10px -15px 0;
}
`

Output:

`
.footer{padding:50px 0;background:#d6d6d6}.footer__navigation ul{display:-webkit-box;flex-wrap:wrap;display:-ms-flexbox;display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap}.footer__navigation li{padding:0 15px}.navigation__main>nav{display:-ms-flexbox;display:-ms-flexbox;display:flex;margin:10px -15px 0}
`

You see there are missing properties, for example:

.footer__navigation ul > list-style-type: none;

**Comment by AndrewEQ** [comment]
You can add this to the config_reduce_declarations.json because they need to be listed for reduction:
```
		"-ms-flex-wrap",
		"flex-wrap"
```
Will have to have a deeper look into what's happening with the "display" property with flex; if you remove the display property and add the above to the config, it works as expected.

**Comment by AndrewEQ** [comment]
Just published the patch and you shouldn't have to do the work arounds I mentioned above.
