### ISSUE TITLE
Wrong css generated!

### ISSUE THREAD

**Issue by do-web** [rbtech/css-purge#24]
Input
`
div:before {
    content: " ";
    width: 0;
    height: 0;
    position: absolute;
    border-style: solid;
    border-width: 0 10px 10px 0;
    border-color: transparent #494949 transparent transparent;
    left: 0px;
    bottom: -10px;
}
`
Output:

`div:before {
    content: " ";
    width: 0;
    height: 0;
    position: absolute;
    border: 0 10px 10px 0 solid transparent #494949 transparent transparent;
    left: 0;
    bottom: -10px;
}
`

Border is a invalid property value.

I also have set this options:

`
{
                trim : false,
                shorten : false,
                verbose : true
            }
`

**Comment by AndrewEQ** [comment]
Never mind, it was a quick fix, just let me know if its not working.
