### ISSUE TITLE
the demo doesn't work

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [rbtech/css-purge#28]
I tryd the demo
https://github.com/rbtech/css-purge/blob/master/demo/css-purge-demo-app.js

a Comma is missing after "shorten : true".
Fixing that, the console logs 

    Output CSS:  p{color:#00f}
    Config File read error: Something went wrong while reading the file, check your config_css.json and please try again.
    { Error: ENOENT: no such file or directory, open 'c:\projectplace\config_css.json'
      errno: -4058,
      code: 'ENOENT',
      syscall: 'open',
      path: 'c:\\projectplace\\config_css.json' }

The output is show for the purgeCSS example as well as for the purgeCSSFiles example.
The config_css.json is located in  /projectroot/node_modules/css-purge/ but got searched in /projectroot/

I've used css-purge@3.0.12

**Comment by AndrewEQ** [comment]
Sorry about that, I was executing it from the root of the project folder before, which I can see is confusing. I really don't know what I was thinking back then, anyways, I made it self sufficient and just updated it.

Thanks for letting me know @Matthias-Hermsdorf and have fun!
