### ISSUE TITLE
Getting /_3token_hck_ error in purged css files

### ISSUE THREAD

**Issue by divakarmanivel** [rbtech/css-purge#30]
After purging css file I am getting this error in multiple lines:
/_3token_hck_1:*/
/_3token_hck_2:*/
/_3token_hck_3:*/
and so on ...

I think you have misspelled the comment line and used an underscore instead of asterisk.

**Comment by AndrewEQ** [comment]
Hi @divakarmanivel, are you using any CSS hacks, could you please share your css?

**Comment by divakarmanivel** [comment]
Hi @AndrewEQ 

So I was able to reproduce it with just a piece of my code.
This is the actual css:
.left-navigation__wrapper_user_imgcont {
	background: url("/user_logo_bg.png") no-repeat center center;
	/*margin-top: 30px;*/
	position: relative;
}

.left-navigation__wrapper_user_avatarImg {
	position: absolute;
	padding: 0;
	bottom: 13%;
	right: 35%;
}

.left-navigation__wrapper_user_img {
	/*padding: 20px;*/
	border: 20px solid transparent;
	width: 144px;
	height: 144px;
	border-radius: 50%;
	cursor: pointer;
}

And this is the purged one:
.left-navigation__wrapper_user_imgcont{background:url("/user_logo_bg.png") no-repeat center center;position:relative}.left-navigation__wrapper_user_avatarImg{position:absolute;padding:0;bottom:13%;right:35%}.left-navigation__wrapper_user_img{/_3token_hck_1:*/border:20px solid transparent;width:144px;height:144px;border-radius:50%;cursor:pointer}

I use vs code to view and edit my files and I also didnt use any CSS hacks.

**Comment by AndrewEQ** [comment]
What are the extra slashes for in these declarations? Those are probably causing it to break.

```
/margin-top: 30px;/
```
```
/padding: 20px;/
```

Should they not be this:

```
/*margin-top: 30px;*/
```
```
/*padding: 20px;*/
```
