### ISSUE TITLE
Ordering is not preserved on selectors

### ISSUE THREAD

**Issue by dinubs** [rbtech/css-purge#31]
Hi, I'm really impressed with css-purge so far. Curious to know if there's an option to preserve the ordering of selectors to match the order they were written initially. Take the code below for example:

```
h1 {
  color: red;
}

h1, h2 {
  color: purple;
}

h1 {
  color: black;
}
```

I would expect it to output the following

```
h1, h2 {
  color: purple;
}

h1 {
  color: black;
}
```

but it actually output this:

```
$ css-purge -c "h1 { color: red; } h1, h2 { color: purple; } h1 { color: black; }"
h1{color:#000}h1,h2{color:purple}
```

As you can tell this will not result in the correct thing showing up, the h1 will be `color: purple` instead of the intended `color: black`.

(note: this example is incredibly scaled down from the actual problem existing in my codebase where we have +300kb of duplicated styles that we're trying to auto-deduplicate until we can solve the actual problem)

**Comment by AndrewEQ** [comment]
Ok, thanks for the feedback @dinubs, will have a look at it asap.

**Comment by AndrewEQ** [comment]
Sorted it out, test and lemme know if you still have an issue.
