### ISSUE TITLE
New "Group Common Decliration Feature" going out live, breaking compilation

### ISSUE THREAD

**Issue by brookscom4580** [rbtech/css-purge#34]
Hello, The "new feature" released in version 3.1.0 went out live instead of dark (for some reason) and is generated erroneously unnested selectors.

Here's a gist for comparison:
https://gist.github.com/brookscom4580/916e012af880e06745b1aaaf234d4fa9

In this gist I've added 4 "files":
- prepurge.css is what we're sending into css-purge
- 3.0.14_post.css is what has been being compiled before version 3.1.0
- 3.1.0_post.css is what we're seeing get compiled with version 3.1.0
- oddity.css calls out the compile issue

I'm sure there is a way to turn off this new feature but given that it went out live it created a quick path to a production issue for us. I expect other people might see the same types of issue as well. Maybe the feature should be set to dark / false by default?

**Comment by AndrewEQ** [comment]
Thanks for the feedback, you're right, maybe was a little too ambitious with this release, will turn it off by default.

**Comment by brookscom4580** [comment]
Much appreciated!

**Comment by AndrewEQ** [comment]
Made the update, lemme know if its still giving issues, thanks.
