### ISSUE TITLE
purging large files

### ISSUE THREAD

**Issue by dominikwilkowski** [rbtech/css-purge#6]
Hey there,

I am working with purge now on big files (2215 selectors) and see that it seems to cut off after 1100 selectors. Might there be a limit we are running into here?
I am still investigating and will let you know when I have more infos.

It also seems to have scramble some selectors:

``` CSS
.table-bordered t>thead>tr>th,.table-bordered t>thead>tr>td
                ^------ this is not in the source anywhere
```

I would gladly provide you with the CSS file I am using and it's result plus verbose log. Just send me a mail(my email is in my npm profile or the `package.json` in my repo) and I'll send you all infos.

Thanks

**Comment by dominikwilkowski** [comment]
Hey @AndrewEQ 
I will have a stab at a rewrite and commit it to another repo for testing. I feel you don't have enough time for this and we are in need for an application such as this. I will credit you and this repo in it and am always open for collaboration or insights.
I will start doing this next week and might use [css.js](https://github.com/jotform/css.js) as a css parser for it. Let's see how we go :)

**Comment by AndrewEQ** [comment]
Yeah, sorry man, lots of things been happening, gonna try squeeze in some time here and there in these next few weeks.

**Comment by cabezayunke** [comment]
Has anyone had a look at this? I'ḿ still seeing this issue with the "@-moz-document url-prefix()" css. Thanks in advance! Good work btw :)

**Comment by AndrewEQ** [comment]
Hi guys, I'm taking some time out to work on a new version, will take this into consideration and let ya know when its out ;)

**Comment by AndrewEQ** [comment]
Just launched the new version!

http://rbtech.github.io/css-purge
