### ISSUE TITLE
Remove duplicates cross files.

### ISSUE THREAD

**Issue by Carreau** [rbtech/css-purge#7]
Hi, 

I'm trying to modify this to be able to remove the rules form one file that are situated in another file. 
I got the basics things, but it seem to be that to be sure, I would need to change the `for (i = 0; i < parsedRulesLen; i++)` to a double for loop, which annoys me a bit. (I'm not super familiar with css-purge and css-parse)

Do you see any better/smart way to do this ? 
Would you be open to a PR that adds the functionality ?

Thanks.

**Comment by ruifortes** [comment]
:+1:

**Comment by AndrewEQ** [comment]
Hi guys, I'm taking some time out to work on a new version, will take this into consideration and let ya know when its out ;)

**Comment by AndrewEQ** [comment]
Sorry for taking so long guys but here's the new version! 

http://rbtech.github.io/css-purge
