### ISSUE TITLE
Is possible generate a list of duplicate selector?

### ISSUE THREAD

**Issue by Mte90** [rbtech/css-purge#9]

**Comment by fassetar** [comment]
+1

**Comment by AndrewEQ** [comment]
I shall look into that feature.

**Comment by AndrewEQ** [comment]
Hi guys, I'm taking some time out to work on a new version, will let ya know as soon as its out.

**Comment by AndrewEQ** [comment]
We launched the new version! 

And yes, our report displays this info :)

http://rbtech.github.io/css-purge
